# Generated by Django 5.2.8 on 2025-12-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Uploaded profile picture', null=True, upload_to='avatars/'),
        ),
    ]
