# Generated by Django 5.2.8 on 2025-12-25 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the snippet')),
                ('html_code', models.TextField(blank=True, help_text='HTML code')),
                ('css_code', models.TextField(blank=True, help_text='CSS styles')),
                ('js_code', models.TextField(blank=True, help_text='JavaScript code')),
                ('environment', models.CharField(choices=[('2d', '2D Web'), ('3d', '3D (Three.js)')], default='2d', help_text='Rendering environment', max_length=2)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization')),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated or uploaded thumbnail', null=True, upload_to='thumbnails/')),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True, help_text='Public snippets appear in feed')),
                ('is_pinned', models.BooleanField(default=False, help_text='Show on user profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forked_from', models.ForeignKey(blank=True, help_text='Original snippet this was forked from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='playground.snippet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='playground.snippet')),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'Likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Comment text', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='playground.snippet')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of viewer')),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='playground.snippet')),
                ('user', models.ForeignKey(blank=True, help_text='User who viewed (if authenticated)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View',
                'verbose_name_plural': 'Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['-created_at'], name='playground__created_fbfdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['user', '-created_at'], name='playground__user_id_35d4be_idx'),
        ),
        migrations.AddIndex(
            model_name='snippet',
            index=models.Index(fields=['slug'], name='playground__slug_c814ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'snippet')},
        ),
    ]
